#!/usr/bin/env python

# +---------------------------+---------+---------+---------+
# | Target Type               | Editor  | Debug   | Release |
# | Tests                     | Yes No  | Yes No  | Yes No  |
# +---------------------------+---------+---------+---------+
# | ./*.cpp                   | Yes Yes | Yes Yes | Yes Yes |
# | ./compiler/**/*.cpp       | Yes Yes | Yes No  | No  No  |
# | ./runtime/**/*.cpp        | Yes Yes | Yes Yes | Yes Yes |
# | ./editor/**/*.cpp         | Yes Yes | No  No  | No  No  |
# | ./tests/*.cpp             | Yes No  | Yes No  | Yes No  |
# | ./tests/compiler/**/*.cpp | Yes No  | Yes No  | No  No  |
# | ./tests/runtime/**/*.cpp  | Yes No  | Yes No  | Yes No  |
# | ./tests/editor/**/*.cpp   | Yes No  | No  No  | No  No  |
# +---------------------------+---------+---------+---------+

import glob
import os

import methods

from misc.utility.scons_hints import *

def glob_custom(path):
    return sorted(glob.glob(path, recursive=True))

Import("env")
Import("env_modules")

env_gdscript3 = env_modules.Clone()

env_gdscript3.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build or (env.debug_features and env["tests"]):
    env_gdscript3.Append(CPPDEFINES=["GDSCRIPT_COMPILER_ENABLED"])
    env_gdscript3.add_source_files(env.modules_sources, glob_custom("compiler/**/*.cpp"))

env_gdscript3.add_source_files(env.modules_sources, glob_custom("runtime/**/*.cpp"))

if env.editor_build:
    env_gdscript3.add_source_files(env.modules_sources, glob_custom("editor/**/*.cpp"))

    #SConscript("editor/script_templates/SCsub")

    ## Those two modules are required for the language server protocol
    #if env["module_jsonrpc_enabled"] and env["module_websocket_enabled"]:
    #    env_gdscript3.add_source_files(env.modules_sources, "./editor/language_server/*.cpp")
    #else:
    #    # Using a define in the disabled case, to avoid having an extra define
    #    # in regular builds where all modules are enabled.
    #    env_gdscript3.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])
    #    # Also needed in main env to unexpose --lsp-port option.
    #    env.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])

if env["tests"]:
    test_headers = []

    env_gdscript3.Append(CPPDEFINES=["TESTS_ENABLED"])

    # NOTE: `./tests/*.h` are added in `modules/SCsub`.
    env_gdscript3.add_source_files(env.modules_sources, "tests/*.cpp")

    if env.debug_features:
        test_headers += glob_custom("tests/compiler/test_*.h")
        env_gdscript3.add_source_files(env.modules_sources, glob_custom("tests/compiler/**/*.cpp"))

    test_headers += glob_custom("tests/runtime/test_*.h")
    env_gdscript3.add_source_files(env.modules_sources, glob_custom("tests/runtime/**/*.cpp"))

    if env.editor_build:
        test_headers += glob_custom("tests/editor/test_*.h")
        env_gdscript3.add_source_files(env.modules_sources, glob_custom("tests/editor/**/*.cpp"))

    # NOTE: `./tests/gdscript_tests.gen.h` must be generated before `modules/modules_tests.gen.h`!
    headers = [os.path.relpath(src, methods.base_folder).replace("\\", "/") for src in test_headers]
    with methods.generated_wrapper("tests/gdscript_tests.gen.h") as file:
        for header in headers:
            file.write(f'#include "{header}"\n')
